<?php

namespace Database\Seeders;

use App\Models\Actividad;
use Illuminate\Database\Seeder;

class ActividadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $actividad = new Actividad();
        $actividad->descripcion = "SIN ACTIVIDAD PROCESAL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "SENTENCIA DE UNICA INSTANCIA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "SENTENCIA INTERLOCUTORIA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "AUTO DE MERO TRÁMITE";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "AUTO DE ADMISIÓN";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "DILIGENCIA DEL ALGUACIL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "DILIGENCIA DE SECRETARIO DEL TRIBUNAL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "DILIGENCIA DEL ACTOR";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "DILIGENCIA DEL DEMANDADO";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "DILIGENCIA DEL TERCERO";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ACTA DE EMBARGO";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "AUDIENCIA PRELIMINAR";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "AUDIENCIA DE JUICIO";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NOTIFICACIÓN";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL ACTOR: DEMANDA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL ACTOR: PROMOCIÓN DE PRUEBAS";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL ACTOR: INFORMES";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL ACTOR: GENERAL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL DEMANDADO: CONTESTACIÓN DEMANDA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL DEMANDADO: CUESTIONES PREVIAS";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL DEMANDADO: PROMOCIÓN DE PRUEBAS";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL DEMANDADO: INFORMES";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL DEMANDADO: GENERAL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL TERCERO: PROMOCIÓN DE PRUEBAS";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL TERCERO: INFORMES";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL TERCERO: GENERAL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DE DENUNCIA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "AUTOCOMPOSICIÓN PROCESAL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "OFICIO DEL TRIBUNAL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NOTA SECRETARIAL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ACTA ANTE INSPECTORÍA DEL TRABAJO";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "SENTENCIA DE PRIMERA INSTANCIA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "SENTENCIA DE SEGUENDA INSTANCIA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO APLICA 1";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "SENTENCIA DEL TSJ";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "MEDIDA CAUTELAR: PROHIBICION DE ENAJENAR";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "MEDIDA CAUTELAR: EMBARGO PREVENTIVO";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "MEDIDA CAUTELAR: EMBARGO EJECUTIVO";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "MEDIDA CAUTELAR: SECUESTRO";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "MEDIDA CAUTELAR: INNOMINADA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "AUTO DE HOMOLOGACIÓN";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ACTA POR INSPECCIÓN JUDICIAL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ACTA NOMBRANDO EXPERTOS";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "POR ADMITIR SOLICITUD";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "PAGO DE EMOLUMENTOS ALGUACIL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 46";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "IMPUGNAC. REC. CAS.";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ACTA DE ENTREVISTA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ACTA DE DECLARACIÓN";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO:FORMALIZAR REC.CAS.";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO ACTOR: CONTESTACION RECONV";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "DILIGENCIA DE INHIBICIÓN";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "AUDIENCIA 323 COPP";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ACTA DE REVISIÓN";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DE REFORMA DE DEMANDA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "AUTO DE ADMISIÓN REFORMA DE DEMANDA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DE RECONVENCIÓN-CONTESTACIÓN";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO CONTESTACIÓN A LARECONVENCIÓN";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "AUTO DE ADMISIÓN DE PRUEBAS";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DE OPOSICIÓN PRUEBAS";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ACTO CONCILIATORIO 257 CPC";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "CONSIGNACIÓN CARTEL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ACTO DE EXHIBICIÓN";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "DILIGENCIA AMBAS PARTES";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 65";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 66";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DE TRANSACCION";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "ESCRITO DEL ACTOR:SUBSANAR CUESTION PREV";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "AUTO DE AVOCAMIENTO";
        $actividad->save();

        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 70";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 71";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 72";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 73";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 74";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 75";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 76";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 77";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 78";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 79";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 80";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 81";
        $actividad->save();

        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 82";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 83";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 84";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 85";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 86";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 87";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 88";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 89";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 90";
        $actividad->save();

        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 91";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 92";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 93";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 94";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 95";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 96";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 97";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 98";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 99";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 100";
        $actividad->save();

        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 101";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 102";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 103";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 104";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 105";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 106";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 107";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 108";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 109";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 110";
        $actividad->save();

        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 111";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 112";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 113";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 114";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 115";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 116";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 117";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 118";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 119";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 120";
        $actividad->save();

        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 121";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 122";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 123";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 124";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 125";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 126";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 127";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 128";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 129";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 130";
        $actividad->save();

        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 131";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 132";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 133";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 134";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 135";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 136";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 137";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 138";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 139";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 140";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 141";
        $actividad->save();
     


        $actividad = new Actividad();
        $actividad->descripcion = "HOMOLOGADO";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "AUTO DEL TRIBUNAL";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "NO EXISTE COD. 144";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "DECISION INTERLOCUTORIA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "EVACUACIÓN DE PRUEBAS";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "DENUNCIA";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "JUICIO DE TACHA DE DOCUMENTO";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "TRAMITAR RECURSO DE CASACION";
        $actividad->save();
        $actividad = new Actividad();
        $actividad->descripcion = "LEVANTAMIENTO DE MEDIDA PROHIBICION ENJ";
        $actividad->save();
           }
}
