<?php

namespace Database\Seeders;

use App\Models\Demanda;
use Illuminate\Database\Seeder;

class DemandaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $demanda = new Demanda();
        $demanda->descripcion = "SIN TIPO DE DEMANDA ASIGNADO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "EJECUCION DE HIPOTECA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "VIA EJECUTIVA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "JUICIO ORDINARIO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "PROCEDIMIENTO DE INTIMACION";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "EJECUCION DE PRENDA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "AMPARO CONSTITUCIONAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RECURSO DE INVALIDACIÓN";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "QUIEBRA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "CUMPLIMIENTO DE CONTRATO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "ACCION MERO DECLARATIVA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "NULIDAD ACTO ADMINISTRATIVO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "INTIMACION HONORARIOS";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "EXPROPIACION";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "PRESCRIPCION AQUISITIVA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DENUNCIA  IRREGULARIDADES ADM.";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "OFERTA REAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RETRACTO LEGAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "COBRO DE BOLIVARES";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "NULIDAD DE REMATE";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "NULIDAD DE CONTRATO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "NULIDAD ACTO REGISTRAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DEMANDA DE SIMULACION";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RECURSO CONTENCIOSO TRIBUTARIO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "EJECUCION DE CREDITO FISCAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "NULIDAD DE ASAMBLEA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "INTERDICTO RESTITUTORIO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RECURSO ANULACION Y CONDENA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "LAUDO ARBITRAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "ACCION REIVINDICATORIA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "NULIDAD DE HIPOTECA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "ACCION DE TERCERIA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "JURISDICCION VOLUNTARIA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "EXTINCIÓN DE HIPOTECA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DERECHO DE PREFERENCIA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "SOLICITUD ENTREGA MATERIAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "NULIDAD DE VENTA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "TERCERÍA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RECURSO DE ANULACION Y AMPARO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "TERCERIA (repetida 38)";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DOTACION DE TIERRAS";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "SERVIDUMBRE DE PASO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "ACUSACION";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "PARTICION DE COMUNIDAD";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "EJECUCION HIPOTECA MOBILIARIA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "EXEQUATUR";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "AUMENT. DE MEJ. Y BIENHECHURIA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "REINVIDICACIÓN";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DENUNCIA IRREGULARIDAD ASMBLEA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RESPONSABILIDAD CIVIL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DESALOJO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "ACCION CAUSAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "CALIFICACIÓN DE DESPIDO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RECURSO CONT.ADMN.FUNCIONARIAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RECURSO CONT.ADM.NULIDAD";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "REGULACION DE CANON";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "NULIDAD DE NORMA LEGAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DENUNCIA DE ESTAFA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "AVOCAMIENTO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "LEVANTAMIENTO DE VELO CORPORAT";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "LABORAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "VERIFICAR";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "VELO CORPORATIVO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DENUNCIA PENAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RECURSO DE HECHO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "JUICIO BREVE";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "PAGO DE MULTAS";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "NULIDAD DE RESOLUCIÓN";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "PRESTACIONES SOCIALES";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "QUERELLA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DAÑOS Y PERJUICIOS";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DIFERENCIA DE PRESTACIONES SOC";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RECURSO JERÁRQUICO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RENDICIÓN DE CUENTAS";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "SIMULACIÓN DE VENTA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RESOLUCIÓN DE CONTRATO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "INTIMACIÓN";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "EJECUCION DE HIPOTECA  (repetido 2)";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DESLINDE";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RECURSO DE QUEJA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "VIA INCIDENTAL (ART 607 CPC)";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "JUICIO DE EXPROPIACIÓN";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "ATRASO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "PAGO DE CONCEPTOS LABORALES";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "COBRO DE OBLIGACIONES DOLARES";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "COBRO DE PRESTACIONES SOCIALES";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RECURSO RECONSIDERACION";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "REINTEGRO ITF";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "TACHA DE FALSEDAD DE DOCUMENTO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "ADMINISTRATIVO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "NULIDAD DE CLAUSULAS CONTRACTU";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "EJECUCION DE PRENDA S.D.P.";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "JUICIO ORAL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "RECLAMO POR DESMEJORA";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "INPSASEL";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DESMEJORA EN EL PUESTO DE TRAB";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "REENGANCHE Y PAG. SAL. CAIDOS";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "DESPIDO INJUSTIFICADO";
        $demanda->save();
        $demanda = new Demanda();
        $demanda->descripcion = "CERT. DE ENFERMEDAD PROF.";
        $demanda->save();
    }
}
