<?php

namespace Database\Seeders;

use App\Models\Estado;
use Illuminate\Database\Seeder;

class EstadoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $estado = new Estado();
        $estado->descripcion = "SIN ESTADO PROCESAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CITACIÓN: PERSONAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CITACIÓN: CARTELES";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CITACIÓN: CORREO CERTIFICA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PROMOCION DE PRUEBAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CITACIÓN: EDICTOS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "OPOSICION A LAS PRUEBAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR ADMITIR: PRUEBAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "EVACUACION DE PRUEBAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR INFORMES: 1° INSTANCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR OBSERVACIONES: INFORMES";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIAR: 1° INSTANCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR: SENTENCIA 1° IN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR APELAR: SENTENCIA 1° INST";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR ANUNCIAR: RECURSO CASACIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR FORMALIZAR: RECURSO CASAC";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR IMPUGNAR: RECURSO CASACIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR RÉPLICA: RECURSO CASACIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CONTRAREPLICA: RECURSO CAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SUSPENDIDO POR: CUESTIÓN PREJU";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR EJECUTAR: SENTENCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR EJECUTAR: CONVENIMIENTO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CALIFICAR ACREENCIAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR INTIMACIÓN: PERSONAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR INTIMACIÓN: CARTELES";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "EJECUTADO PARCIALMENTE";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR REGULACIÓN: COMPETENCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOMBRAR: DEFENSOR AD-LITEM";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CONTESTACIÓN: DEMANDA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR OPONER: CUESTIONES PREVIAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "DESISTIMIENTO: ACCIÓN: HOM/CUM";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR EJERCER: RECURSO DE HECHO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR APELAR: SENTENCIA INTERLOC";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIAR: CUESTIONES PR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIAR: INCIDENCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SE CUMPLIÓ LO DECIDIDO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CITAR: DEFENSOR AD LITEM";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIAR: RECUR DE HECHO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "ACUMULACION A OTRO JUICIO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SE DESCONOCE EDO. PROCESAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR PUBLICAR: CARTEL DE REMATE";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DEMANDAR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SOLICITAR: EJECUCIÓN FORZO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DISTRIBUIR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "DECLINATORIA DE COMPETENCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR JURAMENTAR: DEFENSOR AD LI";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR: PROCURADOR GRAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SOLICITAR: EJECUCIÓN VOL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIAR: REG COMPETENCI";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR: SENT CUEST PREV";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "CONVENIMIENTO HOMOLOGADO/CUMPL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR EJERCER: RECURSO CASACIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DECIDIR: CONSULTA SUPERIOR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIAR: 2° INS/ INTERL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR ADMITIR: DEMANDA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CONTESTAR: RECONVENCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR HOMOLOGAR: TRANSACCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR PROMOVER: PRUEBAS 2° INSTA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR INFORMES: 2° INSTANCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR REENVIAR: SENTENCIA/CASACI";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIAR 2a. INSTANCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR: SENTENCIA INTER";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR EJECUTAR: TRANSACCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR HOMOLAGAR: DESIST/ACCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CELEBRAR: JUNTA ACREEDORES";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR FIJAR: DEBATE ORAL/PÚBLICO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR: REANUDACIÓN CAU";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SOLICITAR: MANDAMIENTO EJE";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR ADMITIR: RECONVENCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CELEBRAR: AUDIENCI PRELIMI";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR: AUDIENCIA CONST";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CELEBRAR: AUDIENCIA DEFIN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CELEBRAR: AUDIENCIA JUICIO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CELEBRAR: AUDIENCIA CONCIL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SENTENCIA: SOBRESEIMIENTO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIAR: RECURSO CASAC";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SOLICITAR: ABOCAMIENTO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR FORMALIZAR: APELACIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SUSPENDIDO POR: INTERVENCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CELEBRAR: AUDIENCIA INFORM";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR ENTREGAR: MANDAMIENTO EJEC";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "MANDAMIENTO EJECUCIÓN BÓVEDA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR APELAR: AUTO DE ADMISIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR APELAR: ADVERSARIO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR APELAR: ADVERSAR Y/O ACTOR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR EJERCER CASACIÓN DEL ADVER";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR EJERCER: CASACIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR EJERCER: CASACIÓN: ADV/ACT";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CELEBRAR: AUDIENCIA ORAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CELEBRAR: ACTO DE REMATE";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "FASE DE INVESTIGACIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR: ABOCAMIENTO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "DESISTIMIENTO: PROCTO: HOM/CUM";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR HOMOLOGAR: DESIST/PROCEDIM";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR HOMOLOGAR: CONVENIMIENTO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR INTENTAR NUEVA ACCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SENTENCIA DE PERENCION";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SENTENCIADO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SUSPENDIDO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "REPOSICIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR EJERCER: RECURSO NULIDAD";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CONTESTAR: APELACIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIAR ÚNICA INSTANCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIAR: SALA POLT. ADM";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR: SENT 2° INST";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CONSIGNAR ESTUDIO ECONÓMIC";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR SENTENCIA DE TSJ";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOMBRAR DEFENSOR AD-LITEM";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR SENT. DEL TSJ";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR ADMITIR: REFORMA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DEMANDAR TB CONTENCIOSOS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SOLICITAR DEV.DE ORIGINALE";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "BUSQUEDA DE ACTIVO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR: ADMITIR TERCERÍA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR SENT REC. HECHO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "COMISIÓN DE AVALUO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR: FIJAR CARTEL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR ADMITIR CONTROL DE LEGALID";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PROLONGACIÓN DE AUD.PRELIMINAR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CELEB. INFORMES SUPERIOR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR: PRESENTAR ESCR. PRUEBAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "NO APLICA 1";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR FIJAR AUDIENC. DE INFORMES";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "NO APLICA 2";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR FIJAR AUDIENC. DE INFORMES repetido(123)";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "NO APLICA 3";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR OIR APELAC. DEL AUT. ADM.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "NO APLICA 4";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR PUBLICAR EDICTO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR SENT. DE PERENC.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR FIJAR AUDIENC. DEFINITIVA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR PUBLICAR SENT. 1º INSTANC.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "IMPUGNAR REC. CASAC.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SENTENCIADO 2° INSTANCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SENTENCIADO 1° INSTANCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SE FIJÓ AUD. ORAL DE INFORMES";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CONTESTACIÓN DE LA PGR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PENDIENTE REMISIÓN ARCHIV JUD.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "FASE INTERMEDIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "FESE DE JUICIO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SE SOLICITÓ PERENCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SE OPUSIERON CUEST. PREVIAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR OIR APELACIÓN DE SENTENCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOMBRAR SINDICO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR ACUMULARSE JUICIO QUIEBRA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DESIGNAR JUEZ";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SENT. DECLINANDO COMPETENCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SOLICITUD DE JUBILACIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "HOMOLOGACIÓN DE TRANSACCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "OPOSICIÓN A LA INT.HON.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR PROMOVER PRUEBAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "NO EXISTE COD. 152";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SE RECIBIO MANDAMIENTO DE EJEC";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "NO APLICA 5";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "EJECUTADA ENTREGA MATERIAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "NO APLICA 6";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SE LIBRÓ MANDAMIENTO EJECUCION";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "JUICIO ORAL Y PUBLICO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "EXTINCION DEL PROCESO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "INFORME DEL SINDICO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOMBRAR JUECES ASOC.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR ADMITIR: APELACIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "AUDIENCIA PRELIMINAR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "LAUDO ARBITRAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CITACIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DICTAR LAUDO ARBITRAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIAR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SE ARCHIVO EL EXPEDIENTE";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "FASE DE JUICIO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "EJECUCIÓN MEDIDA PREVENTIVA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PERENCIÓN DE LA INSTANCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "ARCHIVO JUDICIAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "EN APELACIÓN. AUDIENC ORAL SUP";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "AUTO DE ADMISION";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SE DIO POR TERMINADO EL JUICIO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SE HOMOLOGÓ TRANSACCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SENTENCIADO TSJ SCC";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR AUDIENCIA CONCLUSIVA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "NO EXISTE COD. 179";
        $estado->save();

        $estado = new Estado();
        $estado->descripcion = "POR CELEBRAR AUD. CONCLUSIVA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "CASO DEVUELTO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "CASO DEVUELTO / PERIMIDO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "DEMANDA INADNISIBLE";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "EN EJECUCIÓN DE SENTENCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "INTERPOSICION DEL RECURSO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PARA EJECUCIÓN DE MEDIDAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PARA SENTENCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PARCIALMENTE CON LUGAR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PARCIALMENTE CON LUGAR repetido(188)";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PERIMIDO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR AVOCAMIEN DE UN NUEVO JUEZ";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DECESIÓN DEL SENIAT";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DECISIÓN DE INDEPABIS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SENTENCIA DE 1° INSTANCIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SOLICITUD EMBARGO MOBILIARIO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SE HOMOLOGÓ DESISTIMIENTO PROC";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "DECISION CORTE DE APELACIONES";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SOL. LEVANTAMIENTO DE MED";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CONGSINAR OBSERVA. INFORME";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR TRAMITAR RECURSO DE CASACI";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "CANCELADO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "CANCELÓ DEUDA EN EL TRIBUNAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "CONDENADO EN COSTAS EL BANCO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "EXPROPIADO-ADQUISICION FORZOSA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "FIJACIÓN DEL CARTEL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "HOMOLOGADO DESISTIM. PROCEDIM.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "INADMITIDA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "NO SE INTIMO A LOS DEMANDADOS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PERENCION NO DECRETADA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CELEBRACION AUDIENCIA ORAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CITAR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DECIDIR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DECIDIR LA PROCURADURIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DISTRIBUIR JUEZ DE JUICIO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR FIJAR AUDIENCIA DE JUICIO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR ABOCAMIENTO DEMA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR ADMISIÓN DEMANDA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR DECISIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR: PGR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR PERIMIR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR PRESCRPCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PRESCRIPCIÓN DE LA ACCIÓN";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PROCESO LLEVADO POR FOGADE";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PROPUESTA DE PAGO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PRUEBAS";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "REACTIVAR EN ARCHIVO JUDIC.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "REFORMA DE DEMANDA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "REPOSICIÓN- POR CITAR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SIN DECIDIR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SOLICITUD ARCHIVO JUDICIAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SUSPENDIDO LEPDHV";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SUSPENDIDO P.G.R.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "TERMINADO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "TRANSACCION JUD. HOMOLOGADA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR SOLIC CARTEL REMATE";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR DECI TSUPERIOR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR CUMPLIM VOLUNTAR SENT";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DESIGNAR DEFENSOR AD LITEM";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR PROVIDENCIA ADMINISTRATIVA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "TERCERÍA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR APERTURA DE CTA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR PGR";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIF. DEF. ADLITEM";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR NOTIFICAR: CUMPL. VOLUNT.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DECRETAR CUMPLIMIENTO VOL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR LIBRAR CARTEL DE REMATE";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR DESIGNAR EXPERTO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "METROARCHIVO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "CUMPLIMIENTO VOLUNTARIO.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "DEVOLUCIÓN ORIGINALES";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "DECIDIDO (PROVIDENCIA ADM.)";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "DECLARADO DESIERTO EL ACTO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "EXTINGUIDO EL PROCESO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "SENTENC INTERLOCUTORIA";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "HOMOLOGADO. ACTIVO.";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POD. JUD. NO TIENE JURISDICCIO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "PODER JUD. SI TIENE JURISDICC";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR ENTREGA MATERIAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "CUMPLIMIENTO PARCIAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "COBRANZA EXTRA JUDICIAL";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "CUMPLIENDO PROPUESTA DE PAGO";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "DECAIMIENTO DE LA ACCION";
        $estado->save();
        $estado = new Estado();
        $estado->descripcion = "POR FIJAR HECHOS CONTRV.";
        $estado->save();
    }
}
