<?php

namespace Database\Seeders;

use App\Models\Externo;
use Illuminate\Database\Seeder;

class ExternoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $externo = new Externo();
        $externo->nombre = "SIN ABOGADO EXTERNO ASIGNADO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BRACHO JOEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "AZPURUA ENRIQUE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MENDOZA, PALACIOS, ACEDO, BOR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RODRIGUEZ MACHADO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SANCHEZ TAREK KATHIB";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ARAUJO PARRA JOSE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ARENAS HUMBERTO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GRISANTI, CALVANI, CALZADILLA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CATALA JOSE AGUSTIN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ARRIETA RAÚL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DOMINGUEZ ALÍ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MILLAN GLADYS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CERTAD & CERTAD";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MORALES BELLO IGOR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LLOAN JUAN FRANCISCO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "TRAVIESO EVANS HUGHES ARRIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ARAQUE RIVAS SIMÓN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DIAZ AGUSTÍN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GARCES JOSÉ VICENTE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BELLO LOZANO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ARAQUE, REYNA ,DE JESUS ,SOSA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LA ROCHE ALBERTO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BENTATA HOET & ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LARES MARTINEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "REYES PEDRO MIGUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ATENCIO,GUANIPA, SANCHEZ & URD";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "OQUENDO ROTONDARO & ASC.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CONCEPCION SEXTON & URDANETA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JORDEN BURT BERENSON & JOHNSON";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MILLER, CASSIDY,LARROCA & LEWI";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GOMEZ PINZON & ASOC";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CLEARY, GOTTLIEB, STEEN & HAMI";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CROES WEVER & TCHONG";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MORGAN & MORGAN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROMERO DE RAMIREZ IMELDA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "D EMPAIRE REINA BERMUDEZ Y AS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "VITALE MARCANO Y PECORARI";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GILMER VILORIA-IVIS PARRA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROJAS ESMERALDA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LEAÑEZ FEDERICO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ORONOZ ALFREDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GARCIA IBSEN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GARCIA MENA GONZALO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DAVILA CARDENAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CASTRO BEJA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CASAS RINCON";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ANA GABRIELA DE GARCIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "REYES CELÍN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MELENDEZ COLMENARES JOEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESTE MIGUEL ANGEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SOLARTE EDER";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PORTILLO DAFNE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROJAS OSWALDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "VASQUEZ MANCERA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BUSTAMANTE IRMA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HERNANDEZ TERESA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GOMEZ MUCCI MIGUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "D´JESUS ALFREDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LEON PARILLI ROBERTO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HURTADO MARIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ISRAEL DAVID";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SARMIENTO SOSA, JOSE G.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GUTIERREZ M. SANTOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "OTAMENDI OSORIO Y ASOC.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BRICEÑO DE ARNESEN ELSA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DIAZ TOVAR ALVARO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "VELOZ,LANSA,SOLARTE Y ASOC.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SANCHEZ NAVEDA OTTO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 70";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "VELAZCO MARIANELLA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BRUZUAL JOSÉ REMBERTO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HARRY D. JAMES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HERNANDEZ ANDRES ELOY";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RODRIGUEZ AUGUSTO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ARAUJO ROLANDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESCRITORIO GIRAN & ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PEREZ SONIA MARÍA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GOMEZ LA ROSA ANDRÉS RAFAEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 80";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FEGHALY CHARLES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SANCHEZ CARLOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BARRETO GUILLERMO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "KOESLING RICARDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ABOGADO DE PLANTA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ITURRIAGA JOSÉ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "AGUERO MARIA MAGDALENA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PIETRI HECTOR JOSÉ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BUSTAMANTE JOSE IGNACIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GRATEROL JATAR ALFONSO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MATA PEDRO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CARVAJAL JOSE MIGUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROCA HELIANA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "VASQUEZ LOPEZ JOSÉ GREGORIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "EGUI LUNA EDMUNDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SALAZAR HERNÁNDEZ MÁXIMO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MONTILLA HORACIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DELGADO MONTILLA ARTURO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "REBOLLEDO ANGEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JARAMILLO LUIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SARMIENTO. NUÑEZ& CUEVAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HURTADO HAYDEE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MONTAÑEZ FIDEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SANCHEZ V. JOSÉ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SALAZAR CARLOTA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GUEVARA LEONARDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROSAS AREVALO ELEAZAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROJAS DURAN JESÚS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DURANT SOTO CRISTINA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RUBIO VICTOR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BAKER BOTTS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RUGIERO RAFAELE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ALVAREZ TULIO ALBERTO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FONSECA HERMES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROMANIELLO CARMINE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DE LA TORRE MARÍA A.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "VERNET CARLOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SALAVARRIA LANDER JOSÉ GETULIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PINTO ALEXIS M.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HERRERA GONZALEZ JULIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CALVO V. MIGUEL A.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CARVAJAL MARVIA LOURDES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "VILLASMIL BRICEÑO FERNANDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "KHALET GEBARA GADIEH";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BOUQUET ALEJANDRO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RAMIREZ ELIZABETH";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LAMEDA LEDY";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BRITO AMILCAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "TREJO PARDI MORELLA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FARIA AMALIA MADALENO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BETANCOURT YUSMILA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PORTELES MENDOZA OMAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ANZOLA GUSTAVO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 134";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DUGARTE MARCOS TULIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESCRITORIO JARAMILLO y ASOC.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GONZALEZ HABRAM";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ARAY PEÑA MARIOSMA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GONZALEZ ROMÁN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DURÁN ALEXANDER JOSE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BILZIN & SUMBER";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CASTILLO CHAVEZ ANTONIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "TRUJILLO WILLIAM";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESCRITORIO FRAGA SANCHEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BERNAY CARMEN HERMINIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "THOMAS ROSMERY y ORTEGA JOSÉ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESPINOZA PRIETO ANTONIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GAMEZ ÑAÑEZ MARGOT";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SUBERO MAURICIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GUILLEN ARMAS HERNANDO ENRIQUE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "TORRES EDGAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SANTOS MICHELENA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BAPTISTA PABLO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CHACÍN MARIA ELENA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DURÁN UVENCIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MAURERA ISIDMAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CHACÓN MARIA EUGENIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GULFO RITO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ECHENIQUE JOSE GREGORIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "URDANETA OSWALDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BENAVIDES JOSÉ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BUFETE B.B. & M.M.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MONTILLA CARLOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROSALES RICARDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "URDANETA CARLOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FLORES LUIS ALEXIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BERRIZBEITIA IGNACIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ARAY FREDY";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NATERA YEPEZ ROGER";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DENKYS FRITZ PAYARES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PIRELA MARCOS VILORIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ACURERO NELSON";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PÉREZ MORA HECTOR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RAMIREZ CARLOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ANIYAR ARMANDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ORTIZ LUIS FERMIN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NAVAS BOSSA Y ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LA VERDE PEDRO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MOSQUERA CARLOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DE LÓPEZ ALEGRÍA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LUGO BETTY";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PROMES VAN DOORNE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "THOMAS, JOHN & CO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DIAZ & KAISER";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GARCÍA JOSÉ LUIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RODRÍGUEZ CAMPINS ALBERTO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PICO SOTILLO ALBERTO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DÍAZ JOAQUÍN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ACOSTA JULIO CESAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MILLARES LEONARDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CONTRERAS DEYANIRA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LANDER RAFAEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PIETRI GABRIELA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MOSSI CESAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RODRÍGUEZ EDGAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CHIRINO VALERO JESÚS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FINOL RAFAEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RODRÍGUEZ DE LÓPEZ ELIZABETH";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SILVA JOSÉ JOAQUÍN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ALTUVE ALFREDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LÓPEZ VILLA RUBÉN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GAMUZ RAFAEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HENRIQUEZ MAURA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "URDANETA ALEJO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CORSI LUIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LESSEUR ERNESTO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LINARES CARLOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LAMEDA EDITH";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROJAS RAMÓN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GANDICA JOSÉ ALEJANDRO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RIVERO LUIS MANUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MONTIEL HENDER";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 213";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MORANTES GUSTAVO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HURTADO FRANCISCO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GRUNBERG BENJAMÍN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CORAO HENRY WALLIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LIRA ELIAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ITRIAGO BORGAS PEDRO MIGUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BERRIOS SAPER ANTONIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MACHADO EGUI MANUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SEIJAS NANCY";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ARANDA CLAVO OSWALDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DÍAZ BLANCO DIRNA/REYES JUAN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SANCHEZ OSCAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GONZALEZ BLANCA CECILIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "TORO MIGUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "WILLIAMS JHONN H.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DÁVILA BETTY";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BENGUIGUI RUTH/ BENG MERCEDES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "REYES SHARIM";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MUJICA ZOILA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 233";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "UGARTE JOSÉ LUIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROMERO DAYSY";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ALVAREZ RUBÍN MANUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HOBAICA ADOLFO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JOHNSON LUDWING";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FILARDO TANIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SPECHT SÁNCHEZ OSCAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "TERÁN SONIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MARTÍNEZ DÍAZ JOSÉ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROJAS JESÚS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ANZOLA JOSÉ ANTONIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ZUBILLAGA SILVA FRANCISCO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "UZCATEGUI ALBERTO R.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MUJICA FRANCISCO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DI BATTISTA DE, TINA F.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MARTÍNEZ MINNORI";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RUSSO MARIELA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DÍAZ SANTOS EDUARDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SUTHERLAND";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BOLÍVAR JANETH";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MUÑOZ SONIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LORETO BERNARDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MONTES JUAN MANUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PICHARDO RAFAEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HAMDAN ADOLFO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MARTÍNEZ ARTURO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GONZALEZ OVIEDO MANUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "OMAÑA BORIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LOTHAR STOLBUN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LANDA JOSE MANUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MAGGIOLO REINA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DURÁN JESÚS ROJAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ZERPA LUIS ELBANO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SANTOS LUIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FERRAO ALEXANDRE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RIVAS JULIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MEIGNEN JOSE RAMON";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MONTERO ALFONZO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DIAZ JOSÉ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MARQUEZ EDUARDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "UZCATEGUI JULIO CESAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ALVARADO ADELINO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JORGE MELECHON";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FRANCISCO MONAGAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HADDAD RAMÓN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PIETRI ALFREDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DOMINGO COUTINHO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BLANCO PEDRO PABLO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RODRÍGUEZ OMAÑA BORIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PINTO ANTONIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NOVOA DIMAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CAMPOS CARMEN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "EDMUNDO PEREZ ARTEAGA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LUIS BOUQUET LEÓN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PEDRO PABLO GIL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HUMBERTO CASTRO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "IBRAHIM GARCÍA AÑEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LOZADA YARISMA NATALIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RAMIREZ JOSE LUIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CUEVAS IVAN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MORALES CASTILLO LESBIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "AZPURUA RODRIGO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NUÑEZ JOSÉ LUIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GARCIA HERNANDEZ RAFAEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HURTADO SONIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RIVAS ANAMELY";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SFARIAS COLOTTO RENEIN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "AGUILAR GORRONDONA EDUARDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MARTÍNEZ MURGA CARLOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MANCERA JORGE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "OLIVO FRANCISCO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RANGEL BARÓN LILLY";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "VARELA DELGADO IVAN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MIRABAL CASTRO GUSTAVO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "AGUANA RAUL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "KURSAN & ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CHACÓN ANDERSON ALEXIS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 311";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "AGUILAR MACHADO SOSA & ASO.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PARRA MORENO EDGAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PEÑA EDGAR VICENTE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BUCARITO VICTOR MANUEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CARREÑO CASTILLO ROSA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RAMÍREZ SENIA RAÚL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ITRIAGO TEODORO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GONZÁLEZ SORBEY";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MARQUEZ TULIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "COLMENAREZ TULIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ALVAREZ ELIO TULIOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 323";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 324";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 325";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO APLICA 1";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 327";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 328";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ABOGADO DE SUDEBAN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JUAN STREDEL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PS & A";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JOSE EDUARDO BARALT";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RODRIGUEZ & MENDOZA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HUMBERTO GAMBOA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "AARON & ASOCIADOS FRED AARONS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "YENY KASBAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ELVIRA DUPOUY";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DUNCAN ESPINA PARRA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JUSTO RAMÓN MORAO ROSAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MANUEL TINEO ARMAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 341";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 342";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MARÍA DE LOS ANGELES GARCIA S.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 344";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CELSO ARNESEN BARRETO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RAFAEL ANTONIO RODRIGUEZ V.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JAVIER GARNICA GUERRA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 348";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 349";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GUSTAVO DOMINGUEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "KHAROLYS MEDINA VERGARA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "OCTAVIO ORTA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ALEJANDRA RODRÍGUEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ODALYS LÓPEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GIOMAR CORREIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MARIANELLA SUAREZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "TRINIDAD AMERICA BETANCOURT";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RAFAEL LUIS PARRELLA SALAZAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 359";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "EDITH SIBONEI CALDERON";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "TANACHIAN & DI PRIZIO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MARÍA BLANCO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NARCISO EDUARDO CORONIEL PALACIOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 364";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ARNESEN PADILLA & ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 366";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RICARDO CRUZ RINCON";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PEDRO NIETO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 369";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FEDERICA ALCALA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ABG. PABLO BRAVO PAREDES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HUMBERTO ENRIQUE TERCERO BELLO TABARES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FRONT CONSULTING";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESCRITORIO JURIDICO BAYED ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "GERARDO CHAVEZ Y OTROS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ZAMORA, DONA & ASOC. ESCRITORIO JURÍDICO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MARIANN SALEM PEREZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 378";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LUIS GERARDO HERNANDEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ADRIAN GUGLIELMELLI";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JOSE ENRIQUE AVELEDO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO APLICA 2";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CENTRO DE ARBITRAJE BOGOTA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MIRIAM ELENA GALLEGOS R.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 385";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ABOGADO DE FOGADE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "BELLORIN & GUZMAN ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CESAR YANEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CONSORCIO MEJIAS SALINAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "EDWARD COLINA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESC JUR PEREIRA & GUANIPA ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESC JURD LOPEZ NAVARRO & ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESCRITO JURIDICO ALVAREZ RUBIN & ASOC";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "KPMG ESCRITORIO JURIDICO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LEOPOLDO VAN GRIEKEN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MANUEL CORONADO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MANUEL CORONADO repetido(396)";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NELSON WALTER VALECILLOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "PÉREZ & CALZADILLA CONSULTORES JURIDICOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RAUL FREITES RUIZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROQUE MENDOZA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ROSICH HIMIOB ROMERO & ABOGADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "WALLIS GUERRERO & ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "XIOMARA GUERRERO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "YOSEPH CRISTINA MOLINA RHR& ABOGADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MORRIS SIERRAALTA PERAZA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MERCEDES Y. MOLINA V.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "OSWALDO J. CONFORTTI";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MARIANELA HEREDIA GONZALEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FRANCISCO GIL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JUAN PABLO SALAZAR";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JOSE GASPAR COTTONI";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO APLICA 3";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JUAN CARLOS ANATO PARRA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO APLICA 4";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JESUS RAMON MATERAN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "EDDY MENDEZ NARANJO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FRANCISCO JUAN NAVARRO CASAÑAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SIN ABOGADO ASIGNADO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JOSE VICENTE GARCES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SANDRA VILLALBA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ZULIA GONZALEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESCRITORIO JUR. MONCADA Y ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JUAN CARLOS LINARES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 425";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESCRITORIO JURIDICO CATAN NAVARRO Y ASOC";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "AURELIO CRISAFULLI TRIMARCHI";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LUIS GIRALDO DUQUE";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 429";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 430";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 431";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "RODRÍGUEZ MENDOZA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FRANCISCO CARRILLO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "DIAZ, REUS & TARG LLP";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JOSE ALBERTO PRIETO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO APLICA 5";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JOSE ALBERTO PRIETO repetido(435)";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CESAR QUINTERO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO APLICA 6";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 440";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ANGEL SOLER RAMIREZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "HECTOR L. MARACANO TEPEDINO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CESAR VALDERRAMA G.";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JENNY ROSALES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "CRISANTO VARGAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FRANCISCO BETANCOURT";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SILVIA VARGAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "VANESSA A. ROJAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FRANK GONZALEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LUIS ENRIQUE LOPEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO APLICA 7";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ALEJANDRO JOSE VIDAL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 453";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LUIS LEÓN HERNANDEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "LUIS LEÓN FERNANDEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JACQUELINE HIDALGO";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 457";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JOSE ALVARO VALERO";
        $externo->save();        
        $externo = new Externo();
        $externo->nombre = "ALEJANDRO GARCIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JOSE SAUL LOPEZ";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "MONSERRAT ELIZABETH PALLARES";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO APLICA 8";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "SIN ABOGADO EXTERNO ASIGNADO repetido(1)";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ODREMAN";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO EXISTE COD. 465";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESCRITORIO JURIDICO VALLENILLA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FICALIA 93 DE CARACAS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "NO APLICA 9";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "FISCALIA";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "ESC.JURI.FIN.SOTO & ASOCIADOS";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "TRIBUNAL DE CONTROL";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JORGE TOMAS MOLINAS HUSBAND";
        $externo->save();
        $externo = new Externo();
        $externo->nombre = "JORGE MOLINA";
        $externo->save();
    }
}
