<?php

namespace Database\Seeders;

use App\Models\Interno;
use Illuminate\Database\Seeder;

class InternoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $interno = new Interno();
        $interno->nombre = "SIN ABOGADO ASIGNADO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "IRMA BERMUDEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "FRANKLIN RUBIO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MARIA G. RAMIREZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "KENY HOLMQUIST H.";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JUDITH GARRIDO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MONICA NIETO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "EMIRO LINARES";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MAYRA TORRES";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "BELEN VELAZCO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "CARLOS ANDRES VARGAS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "LEYDA PORRAS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "OLGA BETANCOURT";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "FERNANDO ANDUEZA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JOSÉ RAMÓN DUDAMEL";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "GUILLERMO VILERA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ROSAURA CUETO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "REINA RODRIGUEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JUAN ESTEBAN CRESPO";
        $interno->tipo = "1";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "CLARITZA RODRÍGUEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MARÍA ALEJANDRA PICOT";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "NO APLICA 1";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "HORACIO RODRIGUEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ALEJANDRO PACHECO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ORLANDO RIOS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "LIBIA HERNANDEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ROMERO ALONSO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JULIO BRACHO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JUAN CARLOS RAMIREZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "YAMILA SANDOVAL";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "BELLAVILLE ROSARIO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "FATIMA ANDARA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "RICARDO GABALDÓN";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ALEJANDRO CARRASCO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "CARMEN FERNANDEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "OMAR MENDOZA";
        $interno->tipo = "1";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "CARMEN FERNANDEZ repetido(34)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MINERVA BALZA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "HECTOR SÁNCHEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "NO APLICA 2";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JUAN TRUJILLO (ASISTENTE LEG)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ELOISA BORJAS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "LUIS ROJAS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "CARMEN J. FERNANDEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ESTHER DURAN";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ROSA ANDREINA CARRASCO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MARÍA SROUR";
        $interno->tipo = "1";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "GISMAR PINTO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MARISOL GUERRERO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "WILFREDO A. CELIS (ASIST. ADM)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JAIRO FERNANDEZ RIVERA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "NIDIA ESTANGA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "SALIX URDANETA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "SALIX URDANETA repetido(52)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MARVICELIS VASQUEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "WILFREDO MAURELL";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JESSIKA CASTILLO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ALFREDO RANGEL";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MARVIN MARCANO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "AGUSTIN GONCALVES";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "FERNANDO ANDUEZA repetido(14)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "RAFAEL ACUÑA VALDIVIESO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ANGELA GARCIA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "CLAUDIA YANEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "HENRY AGUILAR";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JEKELL MIERES";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "LISMAR GARCIA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "LORIS CAMARGO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "LUDWING LOPEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "DANAYZETH";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "SIN ABOGADO ASIGNADO repetido(1)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "CARMEN RENGIFO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MARIA DEL PILAR CHAVEZ LEON";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "EDGARD SANSONETTI";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "NIUSMAN ROMERO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ANA SILVA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ANA SILVA repetido(76)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ANA ALVAREZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "KARELIA CARDONE";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MANUEL CORONADO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MARTHA ALVAREZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "YAURI PAEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "WILFREDO A. CELIS repetido(49)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "DECISION CORTE DE APELACIONES";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "CAROLINA PANTOJA (ASIT. ADM.4)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "LUISANA ANGULO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "GABRIEL CERTAIN";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MARIANGELA ALMARZA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "NELSON MELENDEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "LUIS FERNANDO CERTAIN";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JORGE PULGARIN";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "LUIS RONDON";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "LESBIA SAVINO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ANGEL MARTINEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MANUEL MARCANO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "AMARY PIRELA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "DELIA BURGOS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MARYORIS ASTUDILLOS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "GLADIS RONDON";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "MIDAISY PEREZ FLORES";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "DIAZ RAFAEL JOSE";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "DUBRASKA MANZANARES";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "RAFAEL NIEVES";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ALFREDO ROJAS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "THODORA MOURAD";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JOSEFINA MÉNDEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "J. LISANDRO SISO A.";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "GABRIELA MEDINA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "GABRIELA MEDINA repetido(108)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "VIOLETA VÁSQUEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "CINDY CAMPOS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "BETTY ESPINOZA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "CESAR FARIAS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JESUS PALENCIA (ASIST.ADM)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "YOENDY MOTA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ROASANA VILORIA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ROSANA VILORIA repetido(116)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "DORIS VILLEGAS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "IGNACIO GUERRA (ASIST. ADM.)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ELSY CISNEROS (ASIST. ADM.)";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "YOLANDA DE AGUIAR";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "LUIS FER.CEBALLOS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "VANESSA FERRARA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "AGUSTIN CAMARGO";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "CARMEN ESPAÑA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "OMARLYN RODRIGUEZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ERLIS PEREZ";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "YOCEIDAN VALERA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "ROBER GARCIA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "DIANEHT OSTOS";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JORGE TOMAS MOLINAS HUSBAND";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JORGE MOLINA";
        $interno->save();
        $interno = new Interno();
        $interno->nombre = "JORGE RAMIREZ";
        $interno->save();
    }
}
