<?php

namespace Database\Seeders;

use App\Models\Juzgado;

use Illuminate\Database\Seeder;

class JuzgadoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SIN JUZGADO ASIGNADO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SUPERIOR CIVIL MERCANTIL BANCARIO TRÁNSITO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL SUPREMO DE JUSTICIA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CORTE CONTENCIOSO ADMINISTRATIVO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUICIO DE TRANSICIÓN DEL TRABAJO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SUPERIORES LABORALES";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SUPERIORES AGRARIOS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CARRERA ADMINISTRATIVA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST. FAMILIA Y MENORE";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SUPERIOR CONTENCIOSO TRIBUTARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "UNITED STATES DISTRICT COURT";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CORTE DE BANCARROTA DTTO. SUR";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNALES BOGOTA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INSTANCIA DE ARUBA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNALES DE JUICIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZG. SUPERIORES CONT. ADM.";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CONTENC. TRIBUTARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CORTE DEL CONDADO DE MIAMI DADE FLORIDA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "DIRECCION DE INQUILINATO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CORTE DE APELACIONES";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SUSTANCIACIÓN MEDIACIÓN Y EJECUCIÓN";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "EJECUCIÓN 1°";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "1° DE CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CICPC";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST CIVIL MERCANTIL BANCARIO TRANSITO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SUPERIOR CIVIL CONTENCIOSO ADMINISTRATIVO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST SUSTANCIACIÓN MEDIAC EJECUC LABORAL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUICIO TRABAJO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "9° REGIÓN CAPITAL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SUP. LABORAL TRANSITORIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST AGRARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SUPERIOR AGRARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST CIVIL MERCANTIL TRANSITO AGRARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CORTE DE 1era INST. DE CURAZAO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "ALTA CORTE DE JUSTICIA DE ANTIGUA Y BARBUDA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CORTE DE APELACIONES DE LOS EUA 11ª CIRCUNSCRIP.";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "T.S.J. DEL REINO DE HOLANDA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "INSPECTORÍAS DEL TRABAJO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CORTE DEL CIRCUITO JUDICIAL 11º DE MIAMI-DADE FL.";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "FISCALIA 4°DEL EDO FALCON CC DELITOS COMUNES";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INSTANCIA PENAL EN FUNCIÓN DE JUICIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "5 DE CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "1 DE ARAGUA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SALVAGUARDA Y ESPECIAL EN BANCOS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "57 DE SALVAGUARDA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 47";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 48";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "10° REGIÓN CAPITAL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 50";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 51";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "MINISTERIO DE FINANZAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "INSPECTORÍA GENERAL DE TRIBUNALES";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 54";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 55";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 56";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 57";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 58";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 59";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 60";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 61";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 62";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL DISCIPLINARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 64";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 65";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 66";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 67";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "3° REGIÓN CAPITAL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "2° EDO FALCÓN";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 70";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 71";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "43º REGIÓN CAPITAL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO APLICA 1";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "INDEPABIS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CORTE PRIMERA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CORTE SEGUNDA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "FEDERACIÓN DEL COLEGIO DE ABOGADOS DE VZLA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO APLICA 2";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO APLICA 3";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PPRIMERA INSTANCIA PENAL DE EJECUCIÓN";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CENTRO ARBITRAJE CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CENTRO DE ARBITRAJE CAMARA CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "INPSASEL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "POR NOTIFICAR ABOCAMIENTO AL DEFENSOR PARA SENTENC";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL 6TO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INSTANCIA DE SUCRE";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO APLICA 4";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "2° PRIMERA INST. C,M,A Y B. EDO. BOLIVAR";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "2° PRIMERA INST. C,M,A Y B. EDO. BOLIVAR (rep. 88)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "4° DE 1RA INSTANCIA C,M Y T. EDO. CARABOBO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "1° C Y M. EDO. ARAGUA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "2° BOLIVAR.";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "1° INST. CIVIL. MERCANTIL Y TRANSITO.";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "43° 1 INST. LABORAL. CARACAS.";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "4° PRIMERA INSTANCIA CIVIL TACHIRA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL PRIMERA INSATANCIA MARITIMO NACIONAL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL SUPERIOR MARITIMO NACIONAL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNALES TRIBUNAL DE PRIMERA INSTANCIA MARITIMO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "4° DE PRIMERA INSTANCIA C.M.T TACHIRA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST CIVIL MERCANTIL Y TRANSITO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "4° PRIMERA INSTANCIA CIVIL TACHIRA (repetido 95)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 102";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 103";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "1° INSTANCIA ITINERANTE EJEC. DE MED.";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 105";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 106";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 107";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 108";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO EXISTE COD. 109";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO APLICA 5";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "AGRARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SIN JUZGADO ASIGNADO (repetido 1)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL DE ARBITRAMENTO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL DE ARBITRAMENTO (repetido 113)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "9° DE CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "AREA METROPOLITANA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "DE LA CIRCUNSCRIPCION JUDICIAL ÁREA METROPO DE CCS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 1° DE 1° INSTANC CIVIL, MERC Y DEL TRÁNSIT";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 1° PRIMERA INSTANCIA AGRARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 12 DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 13 DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 14 DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 15 DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 18 DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 19 DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 2 DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 3° PRIM INST CIV, MERC, Y DE TRANSITO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 4° DE 1° CIVIL, MERCANTIL Y DEL TRANSITO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 6 DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 6° DE 1° EN LO CIV. MERC. TRANS. Y BANCAR";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 8° DE 1° INST CIVIL, MERC, TRANS Y BANCARI";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DÉCIMO CUARTO DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DECIMO DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DÉCIMO DE MUNICIPIO (repetido 133)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DECIMO NOVENO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DECIMO OCTAVO DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DÉCIMO SÉPTIMO DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DÉCIMO SEXTO DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DEL MUNICIPIO BOLIVAR";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DEL MUNICIPIO MIRANDA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DEL MUNICIPIO URBANEJA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DUODÉCIMO DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO UNDECIMO DE PRIMERA INSTANCIA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO VIGESIMO CUARTO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO VIGÉSIMO CUARTO DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO VIGÉSIMO PRIMERO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO VIGESIMO PRIMERO DE MUNICIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST CIV, MERC, AGRA, TRANS Y TRABA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST CIV, MERC, TRANS, Y DEL TRAB";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST CIV, MERCANTIL, TRÁNSITO Y BANCARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST CIVIL, MERC Y DEL TRÁNSITO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST CIVIL, MERC, AGRA, Y TRANSITO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INSTANCIA CIV MER AGRA Y TRAN";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INSTANCIA CIVIL, MERCANTIL, AGRARIO Y TRAN";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SENIAT";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL 4° DE 1° INST DE SM Y E DEL TRAB";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL CUARTO DE PRIMERA INSTANCIA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL SUPERIOR DE LO CONT TRIBUTARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SUPERIOR EN LO CIVIL Y MERCANTIL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INST. CIVIL, MERC. Y TRANS.";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "EJECUTOR DE MEDIDAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INSTANCIA DE PROTECCION, AL NIÑO, NIÑA Y A";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL 3° EN FUNCIONES DE CONTROL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUNAL EN FUNCIONES DE CONTROL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZ. SUP. SÉPTIMO CONT. TRIBUTARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO SUPERIOR 2° CONTENCIOSO TRIBUTARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO SUPERIOR 3° CONTENCIOSO TRIBUTARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO SUPERIOR 9° CONTENSIOSO TRIBUTARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO SUPERIOR 6° CONTENSIOSO TRIBUTARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "VIGÉSIMO (20°)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SERMAT";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZG.4 MUNICIO. URB. ESTADO NVA.ESPARTA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZG.2° DE 1RA. INST.C Y M EDO, NVA, ESPARTA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 1° DE 1RA. INST. C.M.T.A. EDO. NVA.ESPARTA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "N/A";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 4TO DE 1ERA INST. CI.M.A.T DE EDO ANZOATE";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZG.1° DE 1RA. INST.C.M.A. Y T. EDO.ANZOATEGUI";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZG CMT Y AGRARIO NUEVA ESP.";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "2° NUEVA ESPARTA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 2° DE 1° INST.C.M.T.A. EDO.PORTUGUESA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO SUP C.M.T.T.M.EDO.NVA.ESPARTA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DE MUNICIPIO N.ESPARTA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO CMB CARABOBO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO SUPERIOR CIVIL, MERC Y TRANS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "1° C.M.T.A NUEVA ESPARTA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "GERMAN";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO DUODECIMO DE 1°INST.CIVIL,MERCANTIL,";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "1° COJEDES";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CIVIL, MERCANTIL, TRÁNSITO Y AGRARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "1° NUEVA ESPARTA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO SUP. 8VO. ÁREA METROPOLITANA DE CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CUARTO SUPERIOR";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SUPERIOR CUARTO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "TRIBUANL SUPERIOR CUARTO CONTENCIOSO TRIBUTARIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "INSPECTORIA DEL TRABAJO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "3° PORTUGUESA (GUANARE)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INSTANCIA ZULIA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "7° REGIÓN CAPITAL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "6° REGIÓN CAPITAL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "1° DEL ZULIA.";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "26°REGION CAPITAL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "5° REGIÓN CAPITAL";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "UNITED STATE COURT";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "4° FALCON";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CUARTO DE FALCON";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CENTRO DE ARBITRAJE DE CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CENTRO ARBITRAJE CARACAS (repetido 81,207)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "CENTRO ARBITRAJE CARACAS (repetido 81,207,208)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "JUZGADO 4O. CIVIL DEL CIRCUITO DE BOGOTÁ";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "3° ZULIA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "3° ZULIA (repetido 210,211)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "NO APLICA 6";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "3° ZULIA (repetido 210,211,213)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "5° DE FALCÓN";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "5° DE FALCÓN (repetido 214)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "ABOGADO EXTERNO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "26 DE MUNCIPIO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "4°ZULIA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "28° DE CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "29° DE CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "30° DE CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "1°DE MERIDA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "93 CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "93° DE CARACAS (repetido 223)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "FISCALIA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "PRIMERA INSTANCIA DE CARUPANO";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "SUPERIOR CONT. ADM. ESTADAL DEL EDO. ZULIA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "2° SUPERIOR DEL EDO. ZULIA";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "1° DE CONTROL DE CARACAS";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "FISCALIA (repetido 225)";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "3° DE ANZOATEGUI";
        $juzgado->save();
        $juzgado = new Juzgado();
        $juzgado->descripcion = "8° DE MARACAIBO. EDO ZULIA";
        $juzgado->save();
    }
}
