<?php

namespace Database\Seeders;

use App\Models\Obligacion;
use Illuminate\Database\Seeder;

class ObligacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $obligacion1 = new Obligacion();
        $obligacion1->descripcion = "SIN NINGUN TIPO DE OBLIGACION";
        $obligacion1->save();
        $obligacion2 = new Obligacion();
        $obligacion2->descripcion = "PAGARÉ";
        $obligacion2->save();
        $obligacion3 = new Obligacion();
        $obligacion3->descripcion = "LÍNEA DE CRÉDITO";
        $obligacion3->save();
        $obligacion4 = new Obligacion();
        $obligacion4->descripcion = "CARTA DE CRÉDITO";
        $obligacion4->save();
        $obligacion5 = new Obligacion();
        $obligacion5->descripcion = "PRÉSTAMO";
        $obligacion5->save();
        $obligacion6 = new Obligacion();
        $obligacion6->descripcion = "CRÉDITO HIPOTECARIO";
        $obligacion6->save();
        $obligacion7 = new Obligacion();
        $obligacion7->descripcion = "LETRA DE CAMBIO";
        $obligacion7->save();
        $obligacion8 = new Obligacion();
        $obligacion8->descripcion = "ARRENDAMIENTO FINANCIERO";
        $obligacion8->save();
        $obligacion9 = new Obligacion();
        $obligacion9->descripcion = "CONTRATO DE CREDITO";
        $obligacion9->save();
        $obligacion10 = new Obligacion();
        $obligacion10->descripcion = "CONTRATO DE TRABAJO";
        $obligacion10->save();
        $obligacion11 = new Obligacion();
        $obligacion11->descripcion = "EXTRACONTRACTUAL NO PUNIBLE";
        $obligacion11->save();
        $obligacion12 = new Obligacion();
        $obligacion12->descripcion = "CONTRATO DE ARRENDAMIENTO";
        $obligacion12->save();
        $obligacion13 = new Obligacion();
        $obligacion13->descripcion = "HONORARIOS JUDICIALES";
        $obligacion13->save();
        $obligacion14 = new Obligacion();
        $obligacion14->descripcion = "CONTRATO DE AUXILIO FINANCIERO";
        $obligacion14->save();
        $obligacion15 = new Obligacion();
        $obligacion15->descripcion = "FUNCIONARIALES";
        $obligacion15->save();
        $obligacion16 = new Obligacion();
        $obligacion16->descripcion = "VERIFICAR";
        $obligacion16->save();
        $obligacion17 = new Obligacion();
        $obligacion17->descripcion = "MULTIPLES OBLIGACIONES";
        $obligacion17->save();
        $obligacion18 = new Obligacion();
        $obligacion18->descripcion = "CUMPLIMIENTO DE CONTRATO";
        $obligacion18->save();
        $obligacion19 = new Obligacion();
        $obligacion19->descripcion = "OTROS";
        $obligacion19->save();
        $obligacion20 = new Obligacion();
        $obligacion20->descripcion = "CONTRATO DE VENTA";
        $obligacion20->save();
        $obligacion21 = new Obligacion();
        $obligacion21->descripcion = "CONDOMINIO";
        $obligacion21->save();
        $obligacion22 = new Obligacion();
        $obligacion22->descripcion = "HECHO PUNIBLE";
        $obligacion22->save();
        $obligacion23 = new Obligacion();
        $obligacion23->descripcion = "CONTRATO DE SERVICIOS";
        $obligacion23->save();
        $obligacion24 = new Obligacion();
        $obligacion24->descripcion = "CONTRATO DE SEGUROS";
        $obligacion24->save();
        $obligacion25 = new Obligacion();
        $obligacion25->descripcion = "ACTO ADMINISTRATIVO";
        $obligacion25->save();
        $obligacion26 = new Obligacion();
        $obligacion26->descripcion = "ACTO JUDICIAL";
        $obligacion26->save();
        $obligacion27 = new Obligacion();
        $obligacion27->descripcion = "SOBREGIRO";
        $obligacion27->save();
        $obligacion28 = new Obligacion();
        $obligacion28->descripcion = "DESCUENTO DE GIRO";
        $obligacion28->save();
        $obligacion29 = new Obligacion();
        $obligacion29->descripcion = "CRÉDITO AGRÍCOLA";
        $obligacion29->save();
        $obligacion30 = new Obligacion();
        $obligacion30->descripcion = "CONTRATO DE FIDEICOMISO";
        $obligacion30->save();
        $obligacion31 = new Obligacion();
        $obligacion31->descripcion = "CONVENIMIENTO EXTRAJUDICIAL";
        $obligacion31->save();
        $obligacion32 = new Obligacion();
        $obligacion32->descripcion = "CONTRATO CUENTA CORRIENTE";
        $obligacion32->save();
        $obligacion33 = new Obligacion();
        $obligacion33->descripcion = "PAGARÉ Y LETRA DE CAMBIO";
        $obligacion33->save();
        $obligacion34 = new Obligacion();
        $obligacion34->descripcion = "CERTIFICADO DE DEPÓSITO";
        $obligacion34->save();
        $obligacion35 = new Obligacion();
        $obligacion35->descripcion = "DEPÓSITO JUDICIAL";
        $obligacion35->save();
        $obligacion36 = new Obligacion();
        $obligacion36->descripcion = "HONORARIOS EXTRAJUDICIALES";
        $obligacion36->save();
        $obligacion37 = new Obligacion();
        $obligacion37->descripcion = "FACTURAS";
        $obligacion37->save();
        $obligacion38 = new Obligacion();
        $obligacion38->descripcion = "TRAVELERS CHEQUES";
        $obligacion38->save();
        $obligacion39 = new Obligacion();
        $obligacion39->descripcion = "TARJETA DE CRÉDITO";
        $obligacion39->save();
        $obligacion40 = new Obligacion();
        $obligacion40->descripcion = "DAÑOS Y PERJUICIOS CONTRACTUAL";
        $obligacion40->save();
        $obligacion41 = new Obligacion();
        $obligacion41->descripcion = "DAÑOS Y PERJUICIOS EXTRACONTRA";
        $obligacion41->save();
        $obligacion42 = new Obligacion();
        $obligacion42->descripcion = "DESPOJO DE LA POSESIÓN";
        $obligacion42->save();
        $obligacion43 = new Obligacion();
        $obligacion43->descripcion = "CREDITO PRENDARIO";
        $obligacion43->save();
        $obligacion44 = new Obligacion();
        $obligacion44->descripcion = "CONTRATO PRELIMINAR DE VENTA";
        $obligacion44->save();
        $obligacion45 = new Obligacion();
        $obligacion45->descripcion = "CONTRATO DE COMODATO";
        $obligacion45->save();
        $obligacion46 = new Obligacion();
        $obligacion46->descripcion = "FRAUDE PROCESAL";
        $obligacion46->save();
        $obligacion47 = new Obligacion();
        $obligacion47->descripcion = "UTILIDAD PÚBICA";
        $obligacion47->save();
        $obligacion48 = new Obligacion();
        $obligacion48->descripcion = "CALIFICACION DE FALTA";
        $obligacion48->save();
        $obligacion49 = new Obligacion();
        $obligacion49->descripcion = "PAGO DE LO INDEBIDO";
        $obligacion49->save();
        $obligacion50 = new Obligacion();
        $obligacion50->descripcion = "NO EXISTE COD. 50'";
        $obligacion50->save();
        $obligacion51 = new Obligacion();
        $obligacion51->descripcion = "NO EXISTE COD. 51";
        $obligacion51->save();
        $obligacion52 = new Obligacion();
        $obligacion52->descripcion = "PAGO DE LO INDEBIDO (repetido 49)";
        $obligacion52->save();
        $obligacion53 = new Obligacion();
        $obligacion53->descripcion = "LABORAL";
        $obligacion53->save();
        $obligacion54 = new Obligacion();
        $obligacion54->descripcion = "PAGO DE CONCEPTOS LABORALES";
        $obligacion54->save();
        $obligacion55 = new Obligacion();
        $obligacion55->descripcion = "CREDIMOVIL";
        $obligacion55->save();
        $obligacion56 = new Obligacion();
        $obligacion56->descripcion = "RESERVA DE DOMINIO";
        $obligacion56->save();
        $obligacion57 = new Obligacion();
        $obligacion57->descripcion = "NO APLICA";
        $obligacion57->save();
        $obligacion58 = new Obligacion();
        $obligacion58->descripcion = "DEUDA TARJETA DE CREDITO";
        $obligacion58->save();
        $obligacion59 = new Obligacion();
        $obligacion59->descripcion = "FIANZA";
        $obligacion59->save();
        $obligacion60 = new Obligacion();
        $obligacion60->descripcion = "MULTA E INTERESES MORATORIOS";
        $obligacion60->save();
        $obligacion61 = new Obligacion();
        $obligacion61->descripcion = "RECURSO CONTENCIOSO NULIDAD";
        $obligacion61->save();
        $obligacion62 = new Obligacion();
        $obligacion62->descripcion = "SOLIC DE REINTEG ITF";
        $obligacion62->save();
        $obligacion63 = new Obligacion();
        $obligacion63->descripcion = "TACHA DOCUMENTO POR VIA PPAL";
        $obligacion63->save();
        $obligacion64 = new Obligacion();
        $obligacion64->descripcion = "VENTA CON RESERVA DE DOMINIO";
        $obligacion64->save();
        $obligacion65 = new Obligacion();
        $obligacion65->descripcion = "COBRO DIFERENCIA PRESTACIONES";
        $obligacion65->save();
        $obligacion66 = new Obligacion();
        $obligacion66->descripcion = "DÉBITO NO RECONOCIDO";
        $obligacion66->save();
        $obligacion67 = new Obligacion();
        $obligacion67->descripcion = "CESION DERECHOS CON RESERV DOM";
        $obligacion67->save();
        $obligacion68 = new Obligacion();
        $obligacion68->descripcion = "MICROCREDITO";
        $obligacion68->save();
        $obligacion69 = new Obligacion();
        $obligacion69->descripcion = "HIPOTECA";
        $obligacion69->save();
        $obligacion70 = new Obligacion();
        $obligacion70->descripcion = "INTIMACION";
        $obligacion70->save();
        $obligacion71 = new Obligacion();
        $obligacion71->descripcion = "COMPRA-VENTA PACTO DE RETRACTO";
        $obligacion71->save();
        $obligacion72 = new Obligacion();
        $obligacion72->descripcion = "PACTO DE RETRACTO";
        $obligacion72->save();
        $obligacion73 = new Obligacion();
        $obligacion73->descripcion = "COBRO PRESTACIONES SOCIALES";
        $obligacion73->save();
        $obligacion74 = new Obligacion();
        $obligacion74->descripcion = "RECURSO CONTENCIOSO TRIBUTARIO";
        $obligacion74->save();
        $obligacion75 = new Obligacion();
        $obligacion75->descripcion = "RESOLUCIÓN DE CONTRATO.";
        $obligacion75->save();
        $obligacion76 = new Obligacion();
        $obligacion76->descripcion = "CREDITO AGROPECUARIO";
        $obligacion76->save();
        $obligacion77 = new Obligacion();
        $obligacion77->descripcion = "INTERDICTO";
        $obligacion77->save();    }
}
